services:
  arkane-web:
    image: ghcr.io/techmee-digital/arkane:latest
    container_name: arkane-web
    ports:
      - "127.0.0.1:5003:5000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - default
      - mysql

networks:
  mysql:
    external: true
