"""Clean start with exclusions column

Revision ID: 1c922067751e
Revises: 
Create Date: 2025-07-25 19:35:36.243090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c922067751e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exclusions', sa.String(length=255), nullable=True))
        batch_op.drop_column('extensions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extensions', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('exclusions')

    # ### end Alembic commands ###
